"""Initial migration

Revision ID: 36e6cc223605
Revises: 
Create Date: 2025-01-06 03:27:43.401096

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "36e6cc223605"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("customer_segmentations")
    op.add_column("products", sa.Column("deleted", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "deleted")
    op.create_table(
        "customer_segmentations",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("customer_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("cluster", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("recency_score", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("frequency_score", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("monetary_score", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "rfm_category",
            postgresql.ENUM("loyal_customer", "occasional_customer", "low_value_customer", "others", "noise", name="rfmcategoryenum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], name="customer_segmentations_customer_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="customer_segmentations_pkey"),
    )
    # ### end Alembic commands ###
